version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  redis:
    image: "redis:alpine"
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=dbapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db
      - redis