# Generated by Django 4.0.3 on 2022-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_agent',
            field=models.CharField(max_length=255),
        ),
    ]
