# Generated by Django 4.0.3 on 2022-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_auth', '0004_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='name',
        ),
    ]
